services:
  goflect:
    build:
      context: .
    image: goflect:latest
    environment:
      - POSTGRES_URL=postgres://username:password@postgres:5432/goflect
      - PORT=8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: goflect
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: